# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('pan_num', models.CharField(max_length=10)),
                ('bank_acc_num', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('pan_num', models.CharField(max_length=10)),
                ('bank_acc_num', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('pan_num', models.CharField(max_length=10)),
                ('bank_acc_num', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
            ],
        ),
    ]
