# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='bank_acc_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='ifsc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='pan_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='owner',
            name='bank_acc_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ifsc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pan_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='bank_acc_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ifsc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pan_num',
            field=models.CharField(max_length=15),
        ),
    ]
