# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20180406_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='owners',
            field=models.ManyToManyField(to='pay.Owner'),
        ),
        migrations.AddField(
            model_name='broker',
            name='tenants',
            field=models.ManyToManyField(to='pay.Tenant'),
        ),
    ]
