# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20180422_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='owners',
            field=models.ManyToManyField(blank=True, to='pay.Owner'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='pay.Tenant'),
        ),
    ]
