# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20180422_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='owners',
            new_name='owner0',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='tenants',
            new_name='tenant0',
        ),
    ]
