# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_auto_20180422_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='owner0',
            new_name='owners',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='tenant0',
            new_name='tenants',
        ),
    ]
